name: iOS CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build and Test
        run: |
          defaults write com.apple.dt.Xcode IDESkipMacroFingerprintValidation -bool YES

          xcodebuild test \
            -project E-Commerce-Solution.xcodeproj \
            -scheme E-Commerce-Solution \
            -destination 'platform=iOS Simulator,name=iPhone 16,OS:18.5' \
            -skipMacroValidation \
            CODE_SIGNING_ALLOWED=NO
            
